rooms:
  room1:
    hall:
      x: 0.213
      y: -0.539
      z: -0.7789
      w: 0.6272
    inside:
      x: 0.578
      y: -1.467
      z: 0.9913
      w: -0.1319
  room2:
    hall:
      x: 1.994
      y: -0.539
      z: -0.6017
      w: 0.7987
    inside:
      x: 2.135
      y: -1.445
      z: 0.9937
      w: -0.1121
  room3:
    hall:
      x: 2.089
      y: 0.5
      z: 0.6357
      w: 0.7719
    inside:
      x: 2.127
      y: 1.276
      z: 0.9931
      w: 0.1171
  room4:
    hall:
      x: 0.246
      y: 0.378
      z: 0.7842
      w: 0.6205
    inside:
      x: 0.721
      y: 1.312
      z: 0.9918
      w: -0.1278
